# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  name = "Useful Links"
  weight = 50

[[main]]
  name = "Hugo"
  parent = "Useful Links"
  pageRef = "https://gohugo.io/documentation/"
  weight = 51

[[main]]
  name = "Blowfish"
  parent = "Useful Links"
  pageRef = "https://blowfish.page/"
  weight = 52

[[main]]
  name = "FlowCV"
  parent = "Useful Links"
  pageRef = "https://flowcv.com/"
  weight = 53

[[main]]
  name = "ImgBB"
  parent = "Useful Links"
  pageRef = "https://imgbb.com/"
  weight = 54

[[main]]
  name = "Pixabay"
  parent = "Useful Links"
  pageRef = "https://pixabay.com/"
  weight = 55

[[main]]
  name = "Unsplash"
  parent = "Useful Links"
  pageRef = "https://unsplash.com/"
  weight = 56

[[main]]
  name = "iLoveIMG"
  parent = "Useful Links"
  pageRef = "https://www.iloveimg.com/"
  weight = 57

[[main]]
  name = "Convertio"
  parent = "Useful Links"
  pageRef = "https://convertio.co/"
  weight = 58

[[main]]
  name = "CloudConvert"
  parent = "Useful Links"
  pageRef = "https://cloudconvert.com/"
  weight = 59

[[main]]
  name = "ssl-check"
  parent = "Useful Links"
  pageRef = "https://tools.keycdn.com/ssl"
  weight = 59

[[main]]
  name = "favicon"
  parent = "Useful Links"
  pageRef = "https://favicon.io/"
  weight = 60

[[main]]
  name = "logo"
  parent = "Useful Links"
  pageRef = "https://logo.com/"
  weight = 61
