baseurl = "https://abhinav.ltd"
languageCode = "en-us"
theme = "hermit-v2"

[languages]
  [languages.en]
    title = "One Step Forward"
    [languages.en.params]
      homeSubtitle = "“The more I learn, the more I realize how much I don't know.” - Albert Einstein"
    weight = 1

enableGitInfo = true
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

[params.author]
  name = "Abhinav.K"
  about = "about-me"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Learn, Document, Share"
  themeColor = "#494f5c"

  footerCopyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  gitUrl = "https://github.com/abhinav1107/personal-blog-source"

  justifyContent = false
  relatedPosts = true
  code_copy_button = true
  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = "\u2026 \u23F2 Reading Time:"
  shareSocial = true

  # your social links
  [[params.socialLinks]]
  name = "github"
  url = "https://github.com/abhinav1107"

  [[params.socialLinks]]
  name = "twitter"
  url = "https://twitter.com/abhinav1107"

  [[params.socialLinks]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/abhinav1107"

  [[params.socialLinks]]
  name = "medium_alt"
  url = "https://medium.com/@abhinav1107"

  [[params.socialLinks]]
  name = "email"
  url = "mailto:abhinav@abhinav.ltd"



[menu]
  [[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 10

  [[menu.main]]
  name = "About"
  url = "about-me/"
  weight = 20
